### PR TITLE
Adding script `sla-import.py`

### LINKED ISSUE #31: Merge script
Hello again,
I just wondered, after looking through the forum, if there was an easy way to merge `.sla` files conveniently (eg, using a python script).

Cheers,
S1SYPHOS

### PR DESCRIPTION
**Pull request by S1SYPHOS**
This will fix #31

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
**Changelog:**
Added a 'saveAs' option (`--output`).

**Comment by S1SYPHOS** [comment]
Why u no merge? Organizing LGM I guess? :+1:

**Comment by aoloe** [comment]
Hi, i'm busy at a conference: https://afgral.org/grafiklabor-2019

... i will be "looking" at it very soon : - )

**Comment by aoloe** [comment]
voilà, now i know why i've delayed the merge! : - )

i think that it should be possible to optionally automatically set the starting page page number based on the previous file last page.

there might be an option to only continue the counting, if the type of numbering is the same (i ii iii iv 1 2 3 4)

what do you think about it?

**Comment by S1SYPHOS** [comment]
Do whatever you please :+1: 
I'm all for it.

**Comment by aoloe** [comment]
sorry, i was wrong, of course the pages will be automatically be numbered according to the current section's information.

this having been said, it still would be interesting to be able to set the sections information (and the type + starting page number) from a script.

i've opened a ticket in the scribus bug tracker:
https://bugs.scribus.net/view.php?id=15683

this scripts is complet. period.

**Pull request merged**
